---
title: "alphabeta"
output: html_document
date: "2024-02-20"
---

```{r}
library(dada2); packageVersion("dada2")
library(phyloseq); packageVersion("phyloseq")
library(Biostrings); packageVersion("Biostrings")
library(ggplot2); packageVersion("ggplot2")
library(phangorn); packageVersion("phangorn")
library(DECIPHER); packageVersion("DECIPHER")
library(vegan); packageVersion("vegan")
#library(DESeq2); packageVersion("DESeq2")
library(tidyr); packageVersion("tidyr")
library(svglite)
library(pairwiseAdonis)
library(biomformat)
library(dplyr)
library(reshape2)
theme_set(theme_bw())

path <- "~/workspace/MPI/SG_MemoryRapamycin/new_rapamycin/"

new_day <- gsub("-", "", as.character(Sys.Date()))
```

```{r}
seqtab.nochim <- readRDS(paste0(path, "analysis/CLEAN_merged_seqtabNochim.rds"))
taxa <- readRDS(paste0(path, "analysis/CLEAN_taxonomy_merged.rds"))

samdf <- read.table(paste0(path, "metadata_rapaInter.csv"), header=T, row.names=1, check.names=F, sep=",")
count_tab <- read.table(paste0(path, "analysis/CLEAN_ASVs_counts_merged.tsv"), 
                        header = T, row.names = 1, check.names = F, sep = "\t")
```

```{r}
dir.create(paste0(path, "analysis/intermediate"))
dir.create(paste0(path, "analysis/plots"))
dir.create(paste0(path, "analysis/plots/alpha_beta_diversity"))
```

```{r}
#################
### Make tree and put into phyloseq
#################
# Make the phylogenetic tree
sequences <- getSequences(seqtab.nochim)
names(sequences) <- sequences
# Run sequence alighment using DECIPHER
alignment <- AlignSeqs(DNAStringSet(sequences), anchor = NA)
# Change sequence alignment outpu to phyDat structure
phang.align <- phyDat(as(alignment, "matrix"), type = "DNA")
# Make distance matrix
dm <- dist.ml(phang.align)
treeNJ <- NJ(dm)
# Internal maximum likelihood
fit = pml(treeNJ, data = phang.align)
# Change negative edges length to 0
fitGTR <- update(fit, k=4, inv = 0.2)
fitGTR <- optim.pml(fitGTR, model = "GTR", optInv = TRUE, optGamma = TRUE, rearrangement = "stochastic", control = pml.control(trace = 0))


ps <- phyloseq(otu_table(seqtab.nochim, taxa_are_rows = FALSE),
sample_data(samdf),
tax_table(taxa), phy_tree(fitGTR$tree))

dna <- Biostrings::DNAStringSet(taxa_names(ps))
names(dna) <- taxa_names(ps)
ps <- merge_phyloseq(ps, dna)
ps <- prune_samples(sample_sums(ps) >= 1, ps)
taxa_names_ps <- paste0("ASV", seq(ntaxa(ps)))

# Root tree
set.seed(123)
phy_tree(ps) <- root(phy_tree(ps), sample(taxa_names(ps), 1), resolve.root =TRUE)
# Check that its rooted
is.rooted(phy_tree(ps))

saveRDS(ps, paste0(path, "analysis/phyloseq_obj_", new_day, ".rds"))

ps <- readRDS(paste0(path, "analysis/phyloseq_obj_", new_day, ".rds"))

#################
### Alpha diversity
#################
write.table(estimate_richness(ps, measures = c("Observed", "Shannon", "Simpson")), paste0(path, "analysis/intermediate/alpha_values_", new_day, ".csv"), sep = ";", quote = F)

pdf(paste0(path,"analysis/plots/alpha_beta_diversity/alpha_Shannon_RGrid_", new_day, ".pdf"))
p = plot_richness(ps, color = "Treatment", measures = c("Shannon"), x = "Age") + theme(legend.title = element_blank()) + geom_point()
p +  scale_color_manual(values = c("#000000", "#5a9f68", "#4170b0", "#c34e0d")) + facet_wrap(~Treatment)
dev.off()

pdf(paste0(path,"analysis/plots/alpha_beta_diversity/alpha_Simpson_RGrid_", new_day,".pdf"))
p = plot_richness(ps, color = "Treatment", measures = c("Simpson"), x = "Age") + theme(legend.title = element_blank()) + geom_point()
p +  scale_color_manual(values = c("#000000", "#5a9f68", "#4170b0", "#c34e0d")) + facet_wrap(~Treatment)
dev.off()

#################
### UniFraq
#################
uf_distance  <- phyloseq::distance(ps, "uUniFrac")
wuf_distance <- phyloseq::distance(ps, "wUniFrac")
# Save distance matrices for python
write.table(as.data.frame(as.matrix(uf_distance)), paste0(path, "analysis/intermediate/unifraq_unweighted_dist_", new_day, ".csv"), sep = ";", quote = F)
write.table(as.data.frame(as.matrix(wuf_distance)), paste0(path, "analysis/intermediate/unifraq_weighted_dist_", new_day, ".csv"), sep = ";", quote = F)
# Add meta for analysis
df_d <- melt(as.matrix(uf_distance), varnames = c("row", "col"))
df_d_new <- data.frame(df_d)
write.table(df_d_new, file = paste0(path, "analysis/intermediate/unifraq_unweighted-melt_", new_day, ".csv"), col.names = TRUE, sep = ";", quote = F)
df_d <- melt(as.matrix(wuf_distance), varnames = c("row", "col"))
df_d_new <- data.frame(df_d)
write.table(df_d_new, file = paste0(path, "analysis/intermediate/unifraq_weighted-melt_", new_day, ".csv"), col.names = TRUE, sep = ";", quote = F)
# Plot
uf_ord <- ordinate(ps, method="PCoA", distance=uf_distance)
pdf(paste0(path,"analysis/plots/alpha_beta_diversity/unifraq_unweighted_PCoA_TreatColor_", new_day, ".pdf"))
plot_ordination(ps, uf_ord, color="Treatment") + theme(aspect.ratio=1) +  scale_color_manual(values = c("#000000", "#5a9f68", "#4170b0", "#c34e0d"))
dev.off()

pdf(paste0(path,"analysis/plots/alpha_beta_diversity/unifraq_unweighted_PCoA_Sex_", new_day, ".pdf"))
plot_ordination(ps, uf_ord, color="Sex")
dev.off()

pdf(paste0(path,"analysis/plots/alpha_beta_diversity/unifraq_unweighted_PCoA_Age_", new_day, ".pdf"))
plot_ordination(ps, uf_ord, color="Age")
dev.off()


wuf_ord <- ordinate(ps, method="PCoA", distance = wuf_distance)
pdf(paste0(path,"analysis/plots/alpha_beta_diversity/unifraq_weighted_PCoA_TreatColor_", new_day, ".pdf"))
plot_ordination(ps, wuf_ord, color="Treatment") + theme(aspect.ratio=1) +  scale_color_manual(values = c("#000000", "#5a9f68", "#4170b0", "#c34e0d"))
dev.off()

pdf(paste0(path,"analysis/plots/alpha_beta_diversity/unifraq_weighted_PCoA_Sex_", new_day, ".pdf"))
plot_ordination(ps, wuf_ord, color="Sex") + theme(aspect.ratio=1)
dev.off()

pdf(paste0(path,"analysis/plots/alpha_beta_diversity/unifraq_weighted_PCoA_Age_", new_day, ".pdf"))
plot_ordination(ps, wuf_ord, color="Age") + theme(aspect.ratio=1)
dev.off()
```

```{r}
#################
### Stacked bar plots of taxa abundance
#################
top20 <- names(sort(taxa_sums(ps), decreasing=TRUE))[1:20]
ps.top20 <- transform_sample_counts(ps, function(OTU) OTU/sum(OTU))
ps.top20 <- prune_taxa(top20, ps.top20)
# Adding geom_bar(stat="identity") To remove black lines around the boxes of the plots
pdf(paste0(path,"analysis/plots/alpha_beta_diversity/barplot_topOTU_", new_day, ".pdf"))
plot_bar(ps.top20, x="Age", fill="Family") + facet_wrap(~Treatment) + geom_bar(stat="identity")
dev.off()

#################
### Heatmap of just firmicutes
#################
comp = subset_taxa(ps, (Phylum =="Firmicutes") | is.na(Phylum))
# Find which rows (samples) have zero for everything
which(rowSums(otu_table(comp), na.rm = TRUE) == 0)
# Remove them
#gpt <- prune_taxa(names(sort(taxa_sums(ps), decreasing=TRUE))[1:100], ps)

pdf(paste0(path,"analysis/plots/alpha_beta_diversity/Heatmap_Family_", new_day, ".pdf"))
(p <- plot_heatmap(comp, "NMDS", "bray", "Treatment", "Family", low="#66CCFF", high="#000033", na.value="white"))
dev.off()

#################
### Rarecurves
#################
pdf(paste0(path,"analysis/plots/alpha_beta_diversity/rarecurve_", new_day, ".pdf"))
rarecurve(t(count_tab), step=20, col=samdf$Diet_color, lwd=2, ylab="ASVs", label=F) #, xlim = c(0, ))
abline(v=(min(rowSums(t(count_tab)))))
dev.off()
```

```{r}
#################
### Beta bray curtis
#################
bray_dist = phyloseq::distance(ps, method="bray", weighted=F)

# Store beta diversity for analysis
df_d <- melt(as.matrix(bray_dist), varnames = c("row", "col"))
df_d_new <- data.frame(df_d)
# Save the dataframe to plot in python
write.table(df_d_new, file = paste0(path, "analysis/intermediate/beta_values-melt_", new_day, ".csv"), col.names = TRUE, sep = ";", quote = F)
# Save the matrix
write.table(as.data.frame(as.matrix(bray_dist)), paste0(path, "analysis/intermediate/beta_bray_values_", new_day, ".csv"), sep = ";", quote = F)

# Continue
bray_ord = ordinate(ps, method="PCoA", distance=bray_dist)
#plot_ordination(ps, bray_ord, color="Treatment", shape = "Age_char") + theme(aspect.ratio=1) +  scale_color_manual(values = c("darkgreen", "gold", "dodgerblue", "red", "black"))
pdf(paste0(path,"analysis/plots/alpha_beta_diversity/beta_PCoA_TreatColor_", new_day, ".pdf"))
plot_ordination(ps, bray_ord, color="Treatment") + theme(aspect.ratio=1, axis.text=element_text(size=14), axis.title=element_text(size=16), plot.title = element_text(size=18)) + geom_point(size = 1) +  scale_color_manual(values = c("#000000", "#5a9f68", "#4170b0", "#c34e0d")) + labs(title = "PCoA/Bray-Curtis")
dev.off()


pdf(paste0(path,"analysis/plots/alpha_beta_diversity/beta_PCoA_Sex_", new_day, ".pdf"))
plot_ordination(ps, bray_ord, color="Sex") + theme(aspect.ratio=1, axis.text=element_text(size=14), axis.title=element_text(size=16), plot.title = element_text(size=18)) + geom_point(size = 1) + labs(title = "PCoA/Bray-Curtis")
dev.off()

pdf(paste0(path,"analysis/plots/alpha_beta_diversity/beta_PCoA_Age_", new_day, ".pdf"))
plot_ordination(ps, bray_ord, color="Age") + theme(aspect.ratio=1, axis.text=element_text(size=14), axis.title=element_text(size=16), plot.title = element_text(size=18)) + geom_point(size = 1) + labs(title = "PCoA/Bray-Curtis")
dev.off()
```














