---
title: "deseq"
output: html_document
date: "2024-02-21"
---

```{r}
suppressPackageStartupMessages(library(dada2))
suppressPackageStartupMessages(library(phyloseq))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(phangorn))
suppressPackageStartupMessages(library(DECIPHER))
suppressPackageStartupMessages(library(vegan))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(Biostrings))
suppressPackageStartupMessages(library(ANCOMBC))
suppressPackageStartupMessages(library(mvabund))
#library(microbial)
theme_set(theme_bw())
path <- "~/workspace/MPI/SG_MemoryRapamycin/new_rapamycin/"

new_day <- gsub("-", "", as.character(Sys.Date()))

setwd("~/workspace/MPI/SG_MemoryRapamycin/new_rapamycin/scripts/")
project_path <- "~/workspace/MPI/SG_MemoryRapamycin/new_rapamycin/"
new_day <- gsub("-", "", as.character(Sys.Date()))
metadata <- read.table("~/workspace/MPI/SG_MemoryRapamycin/new_rapamycin/metadata_rapaInter.csv", sep = ";", header = T, row.names = 1, stringsAsFactors = F, comment.char = "")
ps <- readRDS("~/workspace/MPI/SG_MemoryRapamycin/new_rapamycin/analysis/phyloseq_obj_20240220.rds")


```

```{r}
# Format sampledata
sample_data(ps)$Treatment <- as.factor(sample_data(ps)$Treatment)
sample_data(ps)$Age <- as.factor(sample_data(ps)$Age)

# Define comparisons
comparisons <- list(
  c("Control", "Rapa Adult"),
  c("Control", "Rapa Early"),
  c("Rapa Adult", "Rapa Early"),
  c("Control", "Rapa Late"),
  c("Rapa Adult", "Rapa Late"),
  c("Rapa Late", "Rapa Early")
)

# Timepoints
timepoints <- c("Young", "Mid", "Old")

# Loop over comparisons
for (comp_pair in comparisons) {
  for (timepoint in timepoints) {
    tryCatch({
      
      # Subset for months and treatments
      comp <- subset_samples(ps, Age %in% timepoint)
      comp <- subset_samples(comp, Treatment %in% comp_pair)
      sample_data(comp)$Treatment <- factor(sample_data(comp)$Treatment, levels = comp_pair)
      print(comp)
      
      # Check if there are samples available for both treatments
      if (length(unique(sample_data(comp)$Treatment)) != length(comp_pair)) {
        # Skip this comparison if samples for both treatments are not available
        next
      }
      
      print(dim(sample_data(comp)))
      
      ds <- phyloseq_to_deseq2(comp, ~Treatment)
      
      # Since these tables have zeroes
      # calculate geometric means prior to estimate size factors
      gm_mean <- function(x, na.rm = TRUE) {
        exp(sum(log(x[x > 0]), na.rm = na.rm) / length(x))
      }
      geoMeans <- apply(counts(ds), 1, gm_mean)
      
      ds <- estimateSizeFactors(ds, geoMeans = geoMeans)
      ds <- DESeq(ds, fitType = "local", test = "Wald")
      
      res <- results(ds)
      alpha <- 0.05
      sigtab <- res[which(res$padj < alpha), ]
      sigtab <- cbind(as(sigtab, "data.frame"), as(tax_table(ps)[rownames(sigtab), ], "matrix"))
      
      # Name of the comparison
      comp_name <- paste(comp_pair, collapse = "")
      
      # Write results to file
      write.table(sigtab, 
                  paste0(project_path, "/analysis/deseq_timepoints_new/", comp_name, "_", timepoint, "_ALL_", new_day, ".csv"), 
                  sep = ";", quote = FALSE, col.names = NA)
    }, error = function(e) {
      cat("Error occurred:", conditionMessage(e), "\n")
    })
  }
}
```




```{r DESeq2}

ps <- readRDS("~/workspace/MPI/SG_MemoryRapamycin/new_rapamycin/analysis/phyloseq_obj_20240220.rds")

sample_data(ps)$Sex <- as.factor(sample_data(ps)$Sex)
ps <- subset_samples(ps, Sex %in% c("f"))

# Format sampledata
sample_data(ps)$Treatment <- as.factor(sample_data(ps)$Treatment)
sample_data(ps)$Age <- as.factor(sample_data(ps)$Age)

# Define comparisons
comparisons <- list(
  c("Control", "Rapa Adult"),
  c("Control", "Rapa Early"),
  c("Rapa Adult", "Rapa Early"),
  c("Control", "Rapa Late"),
  c("Rapa Adult", "Rapa Late"),
  c("Rapa Late", "Rapa Early")
)

# Timepoints
timepoints <- c("Young", "Mid", "Old")

# Loop over comparisons
for (comp_pair in comparisons) {
  for (timepoint in timepoints) {
    tryCatch({
      
      # Subset for months and treatments
      comp <- subset_samples(ps, Age %in% timepoint)
      comp <- subset_samples(comp, Treatment %in% comp_pair)
      sample_data(comp)$Treatment <- factor(sample_data(comp)$Treatment, levels = comp_pair)
      print(comp)
      
      # Check if there are samples available for both treatments
      if (length(unique(sample_data(comp)$Treatment)) != length(comp_pair)) {
        # Skip this comparison if samples for both treatments are not available
        next
      }
      
      print(dim(sample_data(comp)))
      
      ds <- phyloseq_to_deseq2(comp, ~Treatment)
      
      # Since these tables have zeroes
      # calculate geometric means prior to estimate size factors
      gm_mean <- function(x, na.rm = TRUE) {
        exp(sum(log(x[x > 0]), na.rm = na.rm) / length(x))
      }
      geoMeans <- apply(counts(ds), 1, gm_mean)
      
      ds <- estimateSizeFactors(ds, geoMeans = geoMeans)
      ds <- DESeq(ds, fitType = "local", test = "Wald")
      
      res <- results(ds)
      alpha <- 0.05
      sigtab <- res[which(res$padj < alpha), ]
      sigtab <- cbind(as(sigtab, "data.frame"), as(tax_table(ps)[rownames(sigtab), ], "matrix"))
      
      # Name of the comparison
      comp_name <- paste(comp_pair, collapse = "")
      
      # Write results to file
      write.table(sigtab, 
                  paste0(project_path, "/analysis/deseq_timepoints_new/", comp_name, "_", timepoint, "_F_", new_day, ".csv"), 
                  sep = ";", quote = FALSE, col.names = NA)
    }, error = function(e) {
      cat("Error occurred:", conditionMessage(e), "\n")
    })
  }
}
```

```{r}
ps <- readRDS("~/workspace/MPI/SG_MemoryRapamycin/new_rapamycin/analysis/phyloseq_obj_20240220.rds")

sample_data(ps)$Sex <- as.factor(sample_data(ps)$Sex)
ps <- subset_samples(ps, Sex %in% c("m"))

# Format sampledata
sample_data(ps)$Treatment <- as.factor(sample_data(ps)$Treatment)
sample_data(ps)$Age <- as.factor(sample_data(ps)$Age)

# Define comparisons
comparisons <- list(
  c("Control", "Rapa Adult"),
  c("Control", "Rapa Early"),
  c("Rapa Adult", "Rapa Early"),
  c("Control", "Rapa Late"),
  c("Rapa Adult", "Rapa Late"),
  c("Rapa Late", "Rapa Early")
)

# Timepoints
timepoints <- c("Young", "Mid", "Old")

# Loop over comparisons
for (comp_pair in comparisons) {
  for (timepoint in timepoints) {
    tryCatch({
      
      # Subset for months and treatments
      comp <- subset_samples(ps, Age %in% timepoint)
      comp <- subset_samples(comp, Treatment %in% comp_pair)
      sample_data(comp)$Treatment <- factor(sample_data(comp)$Treatment, levels = comp_pair)
      print(comp)
      
      # Check if there are samples available for both treatments
      if (length(unique(sample_data(comp)$Treatment)) != length(comp_pair)) {
        # Skip this comparison if samples for both treatments are not available
        next
      }
      
      print(dim(sample_data(comp)))
      
      ds <- phyloseq_to_deseq2(comp, ~Treatment)
      
      # Since these tables have zeroes
      # calculate geometric means prior to estimate size factors
      gm_mean <- function(x, na.rm = TRUE) {
        exp(sum(log(x[x > 0]), na.rm = na.rm) / length(x))
      }
      geoMeans <- apply(counts(ds), 1, gm_mean)
      
      ds <- estimateSizeFactors(ds, geoMeans = geoMeans)
      ds <- DESeq(ds, fitType = "local", test = "Wald")
      
      res <- results(ds)
      alpha <- 0.05
      sigtab <- res[which(res$padj < alpha), ]
      sigtab <- cbind(as(sigtab, "data.frame"), as(tax_table(ps)[rownames(sigtab), ], "matrix"))
      
      # Name of the comparison
      comp_name <- paste(comp_pair, collapse = "")
      
      # Write results to file
      write.table(sigtab, 
                  paste0(project_path, "/analysis/deseq_timepoints_new/", comp_name, "_", timepoint, "_M_", new_day, ".csv"), 
                  sep = ";", quote = FALSE, col.names = NA)
    }, error = function(e) {
      cat("Error occurred:", conditionMessage(e), "\n")
    })
  }
}
```

```{r}
ps <- readRDS("~/workspace/MPI/SG_MemoryRapamycin/new_rapamycin/analysis/phyloseq_obj_20240220.rds")

# Format sampledata
sample_data(ps)$Treatment <- as.factor(sample_data(ps)$Treatment)
sample_data(ps)$Age <- as.factor(sample_data(ps)$Age)

# Define comparisons
comparisons <- list(
  c("Control"),
  c("Rapa Adult"),
  c("Rapa Early"),
  c("Rapa Late")
)

# Timepoints
timepoints <- c("Young", "Mid", "Old")
# Loop over comparisons
for (comp_pair in comparisons) {
  for (timepoint in timepoints) {
    tryCatch({
      
      # Subset for months and treatments
      comp <- subset_samples(ps, Age %in% timepoint)
      comp <- subset_samples(comp, Treatment %in% comp_pair)
      sample_data(comp)$Sex <- factor(sample_data(comp)$Sex, levels = c("f", "m"))
      
      print(dim(sample_data(comp)))
      
      ds <- phyloseq_to_deseq2(comp, ~Sex)
      
      # Since these tables have zeroes
      # calculate geometric means prior to estimate size factors
      gm_mean <- function(x, na.rm = TRUE) {
        exp(sum(log(x[x > 0]), na.rm = na.rm) / length(x))
      }
      geoMeans <- apply(counts(ds), 1, gm_mean)
      
      ds <- estimateSizeFactors(ds, geoMeans = geoMeans)
      ds <- DESeq(ds, fitType = "local", test = "Wald")
      
      res <- results(ds)
      alpha <- 0.05
      sigtab <- res[which(res$padj < alpha), ]
      sigtab <- cbind(as(sigtab, "data.frame"), as(tax_table(ps)[rownames(sigtab), ], "matrix"))
      
      # Write results to file
      write.table(sigtab, 
                  paste0(project_path, "/analysis/deseq_timepoints_new/Sex", comp_pair, "_", timepoint, "_", new_day, ".csv"), 
                  sep = ";", quote = FALSE, col.names = NA)
    }, error = function(e) {
      cat("Error occurred:", conditionMessage(e), "\n")
    })
  }
}
```




```{r}
# Check that all our timepoints have OTUs fitting to negative binomial and can therefore be analyzed by deseq2
for (i in 1:length(timepoint)){
  comp <- subset_samples(aldr_comp, Age %in% timepoint[i])
  nb <- manyglm(otu_table(comp) ~ sample_data(comp)$Treatment, family = "negative_binomial")
  pdf(paste0("~/workspace/MPI/SG_MemoryRapamycin/analysis/deseq_timepoints/neg_binom_", timepoint[i], "_M_", new_day, ".pdf"))
  plot(nb)
  dev.off()
}
```
